version: "3.9"

services:
  victorina:
    container_name: victorina
    build:
      context: .
      dockerfile: dockerfile_victorina
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    command: bash -c "
      alembic upgrade head
      && uvicorn main:app --host ${HOST} --port ${PORT} --workers ${UVICORN_WORKERS}
      "
    depends_on:
      - postgres


  postgres:
    container_name: postgres_victorina
    image: postgres:13-alpine3.15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_volume:

